### ISSUE TITLE
--check flag

### ISSUE THREAD

**Issue by niluxv** [msrd0/cargo-doc2readme#33] opened 2021-11-04 12:10 UTC
I use `cargo doc2readme` to generate my readmes for crates, and would be interested in checking the readme to be up to date in CI. For this, it would be useful if `cargo doc2readme` offered a `--check` flag similar to e.g. `cargo fmt --check`.

**Comment by msrd0** [comment] 2021-11-04 12:15
Duplicate of #19. Feel free to share implementation ideas if you have any.

**Closed by msrd0** 2021-11-04 12:15 UTC

**Comment by niluxv** [comment] 2021-11-04 14:15
I'm sorry. Hadn't seen that issue.
